import React, { useState } from 'react'
import { Card, CardHeader, CardContent } from '../components/ui'
import { Select, Button } from '../components/ui'
import { RevenueAnalytics } from '../components/reports/RevenueAnalytics'
import { OccupancyAnalytics } from '../components/reports/OccupancyAnalytics'
import { ReportGenerator } from '../components/reports/ReportGenerator'
import AdvancedAnalyticsDashboard from '../components/analytics/AdvancedDashboard'
import { BusinessIntelligenceSystem } from '../components/analytics/BusinessIntelligenceSystem'
import DailyAnalytics from '../components/analytics/DailyAnalytics'
import { Badge } from '../components/ui/badge'
import { RoleSwitcher } from '../components/common/RoleSwitcher'
import { exportToCSV, formatDateTime, getRevenueAmount } from '../utils/helpers'
import { isCurrentlyParked } from '../utils/statusHelpers'
import { useParkingData } from '../hooks/useParkingData'
import { useUserRole } from '../hooks/useUserRole'
import { useReportGeneration } from '../hooks/useReportGeneration'
import type { ParkingEntry } from '../types'

// This is a backup of the original analytics-focused reports page
// The new ReportsPage.tsx will focus specifically on report generation